In [1]:
print('hello world')

hello world


In [18]:
import torch
x=torch.arange(12).reshape((3,4))
print(x)
print(x.sum(dim=1))
shapex=x.shape
numelx=x.numel()
X=x.reshape(3,4)# 不会重新分配内存，xX会互相影响,可以用x.clone()
O=torch.zeros((2,3,4,5,6))
I=torch.ones((2,3,5))
Ran=torch.randn(3,4,5)


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([ 6, 22, 38])


In [26]:
import torch
x=torch.arange(12*5).reshape((3,4,5))
print(x)
y=x.sum(dim=[1,2],keepdim=True)
print(y)
print(y.shape)

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])
tensor([[[190]],

        [[590]],

        [[990]]])
torch.Size([3, 1, 1])


In [2]:
X=torch.ones((2,3))
Y=2*torch.ones((2,3))
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y # 不用切边id不一样,
print('id(Z):', id(Z))
Z+=Y
print('id(Z):', id(Z))

id(Z): 1920994271376
id(Z): 1920994271376
id(Z): 1920994271376


访问元素
```python
[1,2]
[1,:]
[1:3,1:]#子区域[1,3)不包含右边
[::3,::2] #步长
```

In [6]:
import torch
x=torch.arange(10)
print(x)
print(x[0::2])
print(x[1::2])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])
tensor([1, 3, 5, 7, 9])


In [7]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [10]:
# 如果没有安装pandas，只需取消对以下行的注释来安装pandas
# !pip install pandas
import pandas as pd

data = pd.read_csv(data_file)
print(data)


   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [28]:
import torch
x=torch.arange(12)
y=torch.arange(12)
dotxy=torch.dot(x,y)
print(dotxy)

tensor(506)


In [41]:
import torch
x=torch.arange(4)
xT=torch.arange(4).reshape((4,1))

A=torch.arange(12).reshape((3,4))

print(A@x)
print(A@xT)
print(x@A.t())

tensor([14, 38, 62])
tensor([[14],
        [38],
        [62]])
tensor([14, 38, 62])
