# 记录一下Pytorch用法

In [7]:
import torch

把列表转化为tensor

In [8]:

a=torch.tensor([[1,2,3],[4,5,6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

一些生成特定tensor的方法

In [22]:
O=torch.zeros(2,3,4,5,6)
I=torch.ones(2,3,5)
Ran=torch.randn(3,4,5)

print(O.shape)
print(Ran.shape)

torch.Size([2, 3, 4, 5, 6])
torch.Size([3, 4, 5])


生成一些同shape的tensor

In [25]:
Z = torch.zeros_like(O)
Z.shape
Z==O

tensor([[[[[True, True, True, True, True, True],
           [True, True, True, True, True, True],
           [True, True, True, True, True, True],
           [True, True, True, True, True, True],
           [True, True, True, True, True, True]],

          [[True, True, True, True, True, True],
           [True, True, True, True, True, True],
           [True, True, True, True, True, True],
           [True, True, True, True, True, True],
           [True, True, True, True, True, True]],

          [[True, True, True, True, True, True],
           [True, True, True, True, True, True],
           [True, True, True, True, True, True],
           [True, True, True, True, True, True],
           [True, True, True, True, True, True]],

          [[True, True, True, True, True, True],
           [True, True, True, True, True, True],
           [True, True, True, True, True, True],
           [True, True, True, True, True, True],
           [True, True, True, True, True, True]]],


         [

In [27]:
I2 = torch.ones_like(I)
I2.shape
I2==I

tensor([[[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]],

        [[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]]])

In [14]:
A=torch.tensor([1,2,3,4,5,6,7,8,9
                ,10,11,12]).reshape(3,4)# 不会重新分配内存，xX会互相影响,可以用x.clone()

访问元素
```python
[1,2]
[1,:]
[1:3,1:]#子区域[1,3)不包含右边
[::3,::2] #步长
```

- shape读取tensor的形状，可以看作是维数从最外边的[]开始数；shape可以用[]读取相应为维度大小
- numel直接得到元素数量

In [15]:
print(a.shape)
print(a.shape[0])
print(a.numel())

torch.Size([2, 3])
2
6
