In [1]:
import torch



In [23]:
A = torch.randint(0,5,size=(2,1))
B= torch.randint(0,5,size=(3,2))

In [24]:
C=torch.matmul(B,A)

In [25]:
print(A)
print(B)
print(C)

tensor([[4],
        [0]])
tensor([[2, 4],
        [3, 4],
        [1, 3]])
tensor([[ 8],
        [12],
        [ 4]])
